#!bin/bash

read -p "String1: " str1
read -p "String2: " str2

if [ "$str1" = "$str2" ]  # you can also use double brackets here
then
	echo "The strings are equal"
else
	echo "The strings not  equal"
fi	

