#!/bin/bash

echo -n "Enter your favorite pet:"
read PET

case "$PET" in
	dog)
		echo "Your favorite pet is dog"
		;;
	cat | Cat)
		
		echo "Your favorite pet is cat"
		;;
	fish | "African turtle")
		echo "Fish or turtle are great"
		;;
	*)
		echo "Your favorite pet is unknown"
esac		
