#!/bin/bash
PS3="select a country :"  #prompt

select  COUNTRY in Germany France USA "United Kingdom"
do
	echo "COUNTRY is $COUNTRY"
	echo "REPLY is $REPLY"
done


#Note: select body can be changed to case statement                                                                         
